Implement msb_status
flucto-gmbh/motion-sensor-box pull request #101
Opened 2023-05-08 12:19 UTC by kawindme

2023-05-19 15:02 UTC, pacjac requested changes
Great code, I like it! Please fix return value of msb_status and consider comments regarding msb_services.

2023-05-19 15:02 UTC, pacjac requested changes
Great code, I like it! Please fix return value of msb_status and consider comments regarding msb_services.

2023-05-19 15:19 UTC, kawindme commented on msb/status/status.py
> +            "description": desc,
Does it "hurt" to send it along? If we omit it, the description would need to be added manually to the dashboard.
I don't have a strong opinion on this, if you confirm I will remove it.

2023-05-19 16:22 UTC, kawindme commented on msb/status/status.py
> +def msb_services() -> dict:
I guess I choose bad names for these properties as they actually are not boolean. For example "active" corresponds to the "ActiveState" as described in the man pages, see e.g. https://www.man7.org/linux/man-pages/man5/org.freedesktop.systemd1.5.html . 
Reading the man-page I also found that using `systemctl status` is not recommended way to read the status, programmatically. Instead, `systemctl show` should be used.
I will rework this part using `show`.

2023-05-19 18:36 UTC, kawindme commented
I reimplemented the msb_services function. Please review again.

2023-05-22 13:43 UTC, pacjac approved these changes

2023-05-22 13:44 UTC, merged