Serial reader
flucto-gmbh/motion-sensor-box pull request #134
Opened 2023-07-23 20:41 UTC by k323r

2023-08-05 09:30 UTC, kawindme requested changes

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +            # Set RTS to low and DTR to high
If this is specific to Vestas controllers, consider defining this in the config.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +        self.measurement_keys = ["pow", "gen", "rtr", "wnd", "pit"]
This should probably be defined in the config.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +        except Exception as e:
Explicitly state exception here. Also, `as e` is not necessary.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +                        buffer = buffer + serial_reader.read(serial_reader.in_waiting).decode()
Explicitly state encoding here., and add encoding to config.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +                        if "1:OVERVIEW" in buffer:
Is this Vestas controller specific, as well?

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +                    except UnicodeError as e:
`as e` not used.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +                        buffer = buffer + serial_reader.read(serial_reader.in_waiting).decode()
Consider using a list as buffer instead. Strings are immutable in python, so for every iteration the old string is discarded, and a new one is created. Using a list and concatenating all string only once should be faster.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +    def extractFloats(self, text) -> str:
snake_case

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +    def read_message(self):
Consider renaming to `receive_messages` (or `read_messages`). (Plural as it is a generator)

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +class SerialReader:
Consider reordering the methods to make it easier to follow. I.e. ascending or descending in call order.

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +    def read_a_message_and_publish(self, message):
`read_message_and_publish`?

2023-08-05 09:30 UTC, kawindme commented on msb/serial/SerialReader.py
> +    def start_loop(self):
`run` or `start`?

2023-08-05 09:30 UTC, kawindme commented on msb/serial/config.py
> +    regex: str = "(\\d*\\.?\\d+)kW\\s*(\\d*\\.?\\d+)rpm\\s*(\\d*\\.?\\d+)rpm\\s*(\\d*\\.?\\d+)m/s\\s*(-?\\d*\\.*\\d*)"
Regex could probably be simplified using `r""` string. The question is how the regex has to be defined in the YAML config. 🤔

2023-08-05 09:30 UTC, kawindme commented on msb/serial/config.py
> +    topic: str = "imu"
The topic does not seem correct.

2023-08-31 02:04 UTC, pacjac commented
I would advise against merging this branch, as it is dated and reflects design that is specific to an ongoing project. A more generalized serial reader will be implemented.

2023-08-31 02:04 UTC, closed without merging