added calibration script
flucto-gmbh/motion-sensor-box pull request #154
Opened 2023-08-17 08:12 UTC by P-Bent

Created a little script to create an image in full HD with autofocus disabled for the manual px-to-meter calibration.

2023-08-17 08:23 UTC, kawindme requested changes

2023-08-17 08:23 UTC, kawindme commented on scripts/calibration_image.sh
Could you provide an example how to use that script? E.g. as a comment in the script.
I assume `$1`  references an argument given to the script (?).
What happens if that parameter is not given?

2023-08-17 11:20 UTC, P-Bent commented on scripts/calibration_image.sh
Incorporated your comment. Now the user needs to input the filename as a seperate input.

2023-08-17 11:30 UTC, kawindme commented on scripts/calibration_image.sh
That was not exactly what I meant, I would assume this does the same as before? But now prompts the user instead of reading from the command line?
I don't have a preference which method to use.
Just if you stick with this please change "filetype" to "file extension".

2023-08-17 12:06 UTC, P-Bent commented on scripts/calibration_image.sh
Changed the wording. ;)

2023-08-18 01:37 UTC, kawindme approved these changes

2023-08-18 09:16 UTC, merged